name: Build Termux Package

on:
  workflow_dispatch: # Permite iniciar o build manualmente
  push: # Opcional: Executa o build quando houver push no repositório
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3 git

    - name: Build Package
      run: |
        ./build-package.sh ./packages/mesa-vulkan-icd-freedreno-dri3
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package-deb
        path: debs/
        
